name = "Progression"
author = "AirOne01"
version = "1.7.10-forge-0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "758350ef453e17ba0fc42624bf29f8be97554f37f53a56b36fe7a88a4aa5a605"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
