name = "Progression"
author = "AirOne01"
version = "1.7.10-forge-0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e40800d904b0e76beee1c8e96c2c0eadb8557dbb41ef9e8b53320d2692dcfbb5"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
